version: "3.9"

services:
  backend:
    build: .
    container_name: bus_booking_backend
    ports:
      - "8080:8080"
    networks:
      - busnet

  frontend:
    build:
      context: ./bus-booking-frontend
    container_name: bus_booking_frontend
    ports:
      - "3000:80"
    networks:
      - busnet

networks:
  busnet:
    driver: bridge
